version: "3.8"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: yakin
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: yakin68
            MYSQL_PASSWORD: devopsturkiye
        networks:
            - yakin
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - yakin

networks:
    yakin:
        driver: bridge
